import { MERIDIAN_BRAND } from "../../constants/brand";
import type { Monaco } from "@monaco-editor/react";

export type MeridianEditorTheme = "meridian-dark" | "meridian-light";

const BRAND_SELECTION_DARK = `${MERIDIAN_BRAND}45`;
const BRAND_SELECTION_LIGHT = `${MERIDIAN_BRAND}32`;

/** Monaco widgets have their own palette beyond syntax and editor surfaces. */
function editorInterfaceColors(dark: boolean): Record<string, string> {
  const background = dark ? "#141414" : "#ffffff";
  const foreground = dark ? "#ffffff" : "#111111";
  const muted = dark ? "#b3b3b3" : "#525252";
  const border = dark ? "#383838" : "#cccccc";
  const accentText = dark ? "#ffffff" : MERIDIAN_BRAND;
  const highlight = dark ? "#383838" : "#eeeeee";
  const crimsonWash = `${MERIDIAN_BRAND}32`;
  const neutralWash = `${dark ? "#ffffff" : "#000000"}18`;
  const colors: Record<string, string> = {
    focusBorder: accentText,
    foreground,
    descriptionForeground: muted,
    errorForeground: dark ? "#ec7f90" : MERIDIAN_BRAND,
    "icon.foreground": muted,
    "textLink.foreground": accentText,
    "textLink.activeForeground": accentText,
    "selection.background": crimsonWash,
    "progressBar.background": MERIDIAN_BRAND,
    "button.background": MERIDIAN_BRAND,
    "button.foreground": "#ffffff",
    "button.hoverBackground": "#821626",
    "input.background": background,
    "input.foreground": foreground,
    "input.border": border,
    "input.placeholderForeground": muted,
    "inputOption.activeBackground": crimsonWash,
    "inputOption.activeForeground": foreground,
    "inputOption.activeBorder": accentText,
    "inputValidation.errorBackground": background,
    "inputValidation.errorBorder": MERIDIAN_BRAND,
    "inputValidation.warningBackground": background,
    "inputValidation.warningBorder": muted,
    "inputValidation.infoBackground": background,
    "inputValidation.infoBorder": border,
    "list.activeSelectionBackground": MERIDIAN_BRAND,
    "list.activeSelectionForeground": "#ffffff",
    "list.activeSelectionIconForeground": "#ffffff",
    "list.inactiveSelectionBackground": highlight,
    "list.inactiveSelectionForeground": foreground,
    "list.focusBackground": highlight,
    "list.focusForeground": foreground,
    "list.focusOutline": accentText,
    "list.hoverBackground": highlight,
    "list.hoverForeground": foreground,
    "list.highlightForeground": accentText,
    "list.focusHighlightForeground": accentText,
    "list.errorForeground": accentText,
    "list.warningForeground": muted,
    "menu.background": background,
    "menu.foreground": foreground,
    "menu.border": border,
    "menu.selectionBackground": highlight,
    "menu.selectionForeground": foreground,
    "menu.separatorBackground": border,
    "editorWidget.background": background,
    "editorWidget.foreground": foreground,
    "editorWidget.resizeBorder": border,
    "editorSuggestWidget.background": background,
    "editorSuggestWidget.foreground": foreground,
    "editorSuggestWidget.border": border,
    "editorSuggestWidget.highlightForeground": accentText,
    "editorSuggestWidget.focusHighlightForeground": accentText,
    "editorSuggestWidget.selectedBackground": highlight,
    "editorSuggestWidget.selectedForeground": foreground,
    "editorSuggestWidget.selectedIconForeground": foreground,
    "editorHoverWidget.background": background,
    "editorHoverWidget.foreground": foreground,
    "editorHoverWidget.border": border,
    "editorHoverWidget.statusBarBackground": highlight,
    "editor.findMatchBackground": crimsonWash,
    "editor.findMatchBorder": accentText,
    "editor.findMatchHighlightBackground": crimsonWash,
    "editor.findMatchHighlightBorder": border,
    "editor.findRangeHighlightBackground": `${dark ? "#ffffff" : "#000000"}10`,
    "editor.selectionHighlightBackground": neutralWash,
    "editor.wordHighlightBackground": neutralWash,
    "editor.wordHighlightStrongBackground": crimsonWash,
    "editor.wordHighlightTextBackground": neutralWash,
    "editorBracketMatch.background": highlight,
    "editorBracketMatch.border": accentText,
    "editorLink.activeForeground": accentText,
    "editorError.foreground": dark ? "#ec7f90" : MERIDIAN_BRAND,
    "editorWarning.foreground": muted,
    "editorInfo.foreground": muted,
    "editorHint.foreground": muted,
    "editorLightBulb.foreground": muted,
    "editorLightBulbAutoFix.foreground": accentText,
    "editorLightBulbAi.foreground": muted,
    "editorInlayHint.background": highlight,
    "editorInlayHint.foreground": muted,
    "peekView.border": border,
    "peekViewTitle.background": background,
    "peekViewTitleLabel.foreground": foreground,
    "peekViewTitleDescription.foreground": muted,
    "peekViewResult.background": background,
    "peekViewResult.fileForeground": foreground,
    "peekViewResult.lineForeground": muted,
    "peekViewResult.selectionBackground": highlight,
    "peekViewResult.selectionForeground": foreground,
    "peekViewResult.matchHighlightBackground": crimsonWash,
    "peekViewEditor.background": background,
    "peekViewEditorGutter.background": background,
    "peekViewEditor.matchHighlightBackground": crimsonWash,
    "peekViewEditor.matchHighlightBorder": accentText,
    "editorOverviewRuler.errorForeground": MERIDIAN_BRAND,
    "editorOverviewRuler.warningForeground": muted,
    "editorOverviewRuler.infoForeground": muted,
    "editorOverviewRuler.findMatchForeground": MERIDIAN_BRAND,
    "editorOverviewRuler.selectionHighlightForeground": muted,
    "editorGutter.addedBackground": muted,
    "editorGutter.modifiedBackground": muted,
    "editorGutter.deletedBackground": MERIDIAN_BRAND,
    "diffEditor.insertedTextBackground": `${dark ? "#ffffff" : "#000000"}18`,
    "diffEditor.insertedLineBackground": `${dark ? "#ffffff" : "#000000"}0c`,
    "diffEditor.removedTextBackground": `${MERIDIAN_BRAND}45`,
    "diffEditor.removedLineBackground": `${MERIDIAN_BRAND}22`,
    "diffEditorGutter.insertedLineBackground": highlight,
    "diffEditorGutter.removedLineBackground": crimsonWash,
    "diffEditorOverview.insertedForeground": muted,
    "diffEditorOverview.removedForeground": MERIDIAN_BRAND,
    "minimap.errorHighlight": MERIDIAN_BRAND,
    "minimap.warningHighlight": muted,
    "minimap.findMatchHighlight": MERIDIAN_BRAND,
    "quickInput.background": background,
    "quickInput.foreground": foreground,
    "quickInputList.focusBackground": highlight,
    "quickInputList.focusForeground": foreground,
    "quickInputList.focusIconForeground": foreground,
    "pickerGroup.foreground": accentText,
    "pickerGroup.border": border,
  };
  for (const symbol of [
    "array", "boolean", "class", "color", "constant", "constructor", "enumerator",
    "enumeratorMember", "event", "field", "file", "folder", "function", "interface",
    "key", "keyword", "method", "module", "namespace", "null", "number", "object",
    "operator", "package", "property", "reference", "snippet", "string", "struct",
    "text", "typeParameter", "unit", "variable",
  ]) colors[`symbolIcon.${symbol}Foreground`] = muted;
  return colors;
}

export function registerMeridianMonacoThemes(monaco: Monaco): void {
  monaco.editor.defineTheme("meridian-dark", {
    base: "vs-dark",
    inherit: false,
    rules: [
      { token: "", foreground: "FFFFFF" },
      { token: "comment", foreground: "999999", fontStyle: "italic" },
      { token: "keyword", foreground: "EC7F90", fontStyle: "bold" },
      { token: "string", foreground: "DDDDDD" },
      { token: "number", foreground: "B3B3B3" },
      { token: "type", foreground: "EC7F90" },
      { token: "tag", foreground: "EC7F90" },
      { token: "invalid", foreground: "EC7F90", fontStyle: "underline" },
    ],
    colors: {
      ...editorInterfaceColors(true),
      "editor.background": "#0a0a0a",
      "editor.foreground": "#ffffff",
      "editor.lineHighlightBackground": "#00000000",
      "editor.lineHighlightBorder": "#383838",
      "editor.selectionBackground": BRAND_SELECTION_DARK,
      "editor.inactiveSelectionBackground": `${MERIDIAN_BRAND}22`,
      "editorLineNumber.foreground": "#858585",
      "editorLineNumber.activeForeground": "#cccccc",
      "editorCursor.foreground": "#ffffff",
      "editorWidget.border": "#383838",
      "editorIndentGuide.background": "#262626",
      "editorIndentGuide.activeBackground": "#383838",
      "editorGutter.background": "#0a0a0a",
      "editorBracketHighlight.foreground1": "#ec7f90",
      "editorBracketHighlight.foreground2": "#b3b3b3",
      "editorBracketHighlight.foreground3": "#ec7f90",
      "editorBracketHighlight.foreground4": "#b3b3b3",
      "editorBracketHighlight.foreground5": "#ec7f90",
      "editorBracketHighlight.foreground6": "#b3b3b3",
      "editorBracketHighlight.unexpectedBracket.foreground": "#ec7f90",
    },
  });

  monaco.editor.defineTheme("meridian-light", {
    base: "vs",
    inherit: false,
    rules: [
      { token: "", foreground: "111111" },
      { token: "comment", foreground: "737373", fontStyle: "italic" },
      { token: "keyword", foreground: "A51C30", fontStyle: "bold" },
      { token: "string", foreground: "404040" },
      { token: "number", foreground: "525252" },
      { token: "type", foreground: "A51C30" },
      { token: "tag", foreground: "A51C30" },
      { token: "invalid", foreground: "A51C30", fontStyle: "underline" },
    ],
    colors: {
      ...editorInterfaceColors(false),
      "editor.background": "#ffffff",
      "editor.foreground": "#111111",
      "editor.lineHighlightBackground": "#eeeeee80",
      "editor.selectionBackground": BRAND_SELECTION_LIGHT,
      "editorLineNumber.foreground": "#737373",
      "editorLineNumber.activeForeground": "#525252",
      "editorCursor.foreground": MERIDIAN_BRAND,
      "editorWidget.border": "#cccccc",
      "editorIndentGuide.background": "#e5e5e5",
      "editorIndentGuide.activeBackground": "#cccccc",
      "editorGutter.background": "#ffffff",
      "editorBracketHighlight.foreground1": "#a51c30",
      "editorBracketHighlight.foreground2": "#525252",
      "editorBracketHighlight.foreground3": "#a51c30",
      "editorBracketHighlight.foreground4": "#525252",
      "editorBracketHighlight.foreground5": "#a51c30",
      "editorBracketHighlight.foreground6": "#525252",
      "editorBracketHighlight.unexpectedBracket.foreground": "#a51c30",
    },
  });
}

export function toMeridianMonacoTheme(
  workspaceTheme: "dark" | "light",
): MeridianEditorTheme {
  return workspaceTheme === "dark" ? "meridian-dark" : "meridian-light";
}
