import { BadRequestException, NotFoundException } from '@nestjs/common';

/**
 * Cleanup is deliberately limited to the prefixes generated by this
 * repository's browser and HTTP integration suites. Keeping this as an exact
 * allow-list prevents a malformed request from turning `startsWith` into a
 * broad user-deletion primitive.
 */
export const ALLOWED_TEST_EMAIL_PREFIXES = [
  'e2e-',
  'int-auth-',
  'int-doc-',
  'int-throttle-',
  'int-workspace-owner-',
] as const;

const allowedPrefixSet = new Set<string>(ALLOWED_TEST_EMAIL_PREFIXES);
const TEST_EMAIL_PATTERN =
  /^(?:e2e-[a-z0-9][a-z0-9._+-]*|int-(?:auth|doc|throttle|workspace-owner)-[a-z0-9][a-z0-9._+-]*)@example\.com$/;

/** Hide every E2E-only route unless the process is explicitly in a safe mode. */
export function assertE2eTestMode(): void {
  if (
    process.env['E2E_TEST'] !== 'true' ||
    process.env['NODE_ENV'] === 'production'
  ) {
    throw new NotFoundException();
  }
}

/** Return an exact, allow-listed prefix or reject the request before any query. */
export function assertTestEmailPrefix(value: unknown): string {
  if (typeof value !== 'string' || !allowedPrefixSet.has(value)) {
    throw new BadRequestException('A recognized test email prefix is required.');
  }
  return value;
}

/**
 * E2E helpers may only operate on synthetic addresses generated by our test
 * suites. Requiring the reserved example.com domain provides a second safety
 * boundary in addition to the known prefix.
 */
export function assertTestEmail(value: unknown): string {
  if (
    typeof value !== 'string' ||
    value.length > 254 ||
    !TEST_EMAIL_PATTERN.test(value)
  ) {
    throw new BadRequestException('A recognized test email is required.');
  }
  return value;
}
